
MOUSEKEY_ENABLE  = yes # Mouse keys(+4700)
BACKLIGHT_ENABLE = yes # Enable keyboard backlight functionality

# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no  # Breathing sleep LED during USB suspend

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
